### ISSUE TITLE
Change in documentation generation?

### ISSUE THREAD

**Issue by mmottl** [dbuenzli/topkg#129]
I cannot make my API documentation work with `gh-pages` anymore.  The `api` subdirectory generated by `topkg publish doc` in my `gh-pages` branch now contains subdirectories `_html`, `_mlds`, and `_odoc`.  The contents of `_html` is what used to be directly within the `api` directory.  Besides breaking documentation links, the problem here is that Jekyll as used by `gh-pages` seems to ignore files and directories starting with an underscore.

Could this please be fixed in `topkg`?  I guess some coordination with the `odoc` maintainers may be helpful to avoid breaking documentation tools in the future.

**Comment by dbuenzli** [comment]
The documentation stuff has always been a bit ad-hoc and ocamlbuild specific, from `topkg help doc`:

```
WARNING. The way this command works is at the moment very ad-hoc and ocamlbuild specific.
```

Since `topkg` does many things that are not relevant to `jbuilder` @samoht has started [`dune-release`](https://github.com/samoht/dune-release) which is supposed to give you the `topkg` release  experience for `dune` projects. I don't know if it solves this problem but in any case I suggest you file an issue there. 

`topkg` is basically in maintenance mode and won't be developed further as far as I'm concerned.

**Comment by mmottl** [comment]
Thanks for the fast reply!  I'll switch over to `dune-release` as soon as it's a little more stable.  Someone there also just ran into the same issue: https://github.com/samoht/dune-release/issues/16
