### ISSUE TITLE
Very sparse instructions on how to build without opam

### ISSUE THREAD

**Issue by martin-neuhaeusser** [dbuenzli/topkg#135]
I am trying to use Logs on Cygwin/Windows, where opam is not fully supported.

Sadly, Logs can be built from scratch (i.e. without opam) only via topkg. The latter again builds only via opam and lacks sufficient (at least for me) instructions for a regular (i.e. opam independent) built.

Therefore I would kindly like to ask if someone who is knowledgable about the build process could add a small script or a paragraph in the readme-files of either of logs or topkg to support such a use case.

**Comment by dbuenzli** [comment]
Any reason why you are not using https://fdopen.github.io/opam-repository-mingw/ ? Logs is supported there. 

Otherwise building is easy, installing is a little bit less since it relies on `opam`'s install files so you'd need the `opam-installer` tool unless you want to process this files yourself. See:

https://github.com/dbuenzli/topkg/blob/master/topkg.opam#L16-L18
https://github.com/dbuenzli/logs/blob/master/opam#L23-L28

Also you if you are using `dune` you may want to checkout this fork https://github.com/dune-universe/logs/tree/duniverse-master which I believe has a dune build system.

**Comment by dbuenzli** [comment]
@martin-neuhaeusser forgot to add, please tell me if nothing suggested fits.

**Comment by martin-neuhaeusser** [comment]
Thank you for again hinting at OCaml for Windows! 

In the meantime, we updated our built environment (that we set up manually in 2015 when OPAM was not really available on Windows) to now use OCaml for Windows. Some things stilll need to be done manually (mostly solver bindings, in our case), but most package that we use are supported now. It is very good to see that OCaml for Windows has matured that much! 

Indeed, this resolved the issue, as Logs installs flawlessly.
