### ISSUE TITLE
Test windows support.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/topkg#28]
Windows support should be tested along two lines

1. Correctness of package installation using `topkg`. This is essential.
2. `topkg` the helper tool works correctly on Windows, this may uncover potential bugs in `bos`.

**Comment by fdopen** [comment]
I found two issues so far:

1)
You need to add two additional quotes here:
https://github.com/dbuenzli/topkg/blob/82e58b073a26cb93065a68b3caa3ae8f19dc7056/src/topkg_os.ml#L192
`strf "%s%s%s%s%s" quote_on_windows cmd stdout stderr quote_on_windows` (simple quotes, not Filename.quote)
See: https://www.borngeek.com/2011/03/22/calls-to-system-in-windows/

(and stdout and stderr above should probably be quoted with `Filename.quote`)

2)
ocamlbuild can't handle backslashes very well, you have to use forward slashes in the generated ocamlbuild calls:

e.g.
`ocamlbuild -use-ocamlfind ... "src/topkg_vcs.cmx" ...`
not:
`ocamlbuild -use-ocamlfind ... "src\topkg_vcs.cmx" ...`

**Comment by dbuenzli** [comment]
Thanks for the feedback and detailed information @fdopen. I pushed two fixes could you please try them. Are you in an `opam` setting ? If so a : 
```
opam pin add topkg -kgit https://github.com/dbuenzli/topkg.git
```
should do.  To be clear can you confirm `v0.7.0` doesn't work at all on Windows without these fixes ?

**Comment by fdopen** [comment]
Yes, topkg doesn't work at all on Windows without the latest two changes.
Now rresult, bos, fmt, logs and fpath can be installed without problems.
(But there aren't any 'test:' sections inside the opam files, so I can't say anything further,...)

**Comment by dbuenzli** [comment]
> Now rresult, bos, fmt, logs and fpath can be installed without problems.

Ok if you confirm me that you can install `topkg-care` and run `topkg` I'll make a new release with the fixes.

**Comment by dbuenzli** [comment]
Oh to install topkg-care:
```
opam pin add topkg-care -kgit https://github.com/dbuenzli/topkg.git
```

**Comment by fdopen** [comment]
Yes, topkg-care can be compiled, too. But beside `topkg help` nothing seem to work. Some examples

topkg build:
`topkg.exe: [ERROR] run ["pkg\\pkg.ml"; "build"]: Exec format error`  (no shebang support on windows,...)

topkg log:
`topkg.exe: [ERROR] run ["less"]: Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist.`
(translation: "An operation was attempted on something that is not a socket.")

topkg doc:
doesn't work because it still uses backslashes ("doc\\api.docdir\\index.html" instead of "doc/api.docdir/index.html"

topkg clean:
`topkg.exe: [ERROR] delete directory _build: _build\src: Permission denied`

topkg lint:
`topkg.exe: [ERROR] run ["ocamlfind"; "lint"; "pkg\\META"]: "An operation was attempted on something that is not a socket."`
`topkg.exe: [ERROR] run ["opam"; "lint"; "opam"]: "An operation was attempted on something that is not a socket."`

**Comment by dbuenzli** [comment]
> Yes, topkg-care can be compiled, too.

Ok so this is enough to grant a new release, it confirms that `topkg-care`'s dependencies are installed correctly which solve 1. above. 

We can now move to 2.

> topkg build:
> topkg.exe: [ERROR] run ["pkg\\pkg.ml"; "build"]: Exec format error (no shebang support on windows,...)

Of course an `ocaml` is missing [here](https://github.com/dbuenzli/topkg/blob/aed6980538ebf475e8d7a6042ccb7287d0ca7e3a/src-care/topkg_care_pkg.ml#L267). Running `pkg/pkg.ml` files directly is not supported on Windows.

> topkg doc:
> doesn't work because it still uses backslashes ("doc\api.docdir\index.html" instead of "doc/api.docdir/index.html"

Yes that's because `topkg-care` uses `Fpath` rather than `Topkg's` poor man file path. `Fpath` does the right thing on windows except `ocamlbuild` doesn't like the right thing.

The `lint` ones are a little bit more obscure what happens if you invoke the tools manually ? 

Maybe it will be easier if can get a Windows setup myself to you maybe have a VM to share ?

**Comment by dbuenzli** [comment]
Regarding `topkg log` does actually `topkg help` work ? It should have the same kind of pager discovery as `cmdliner` and people reported to me that it worked on Windows (but maybe that was cygwin).

**Comment by dbuenzli** [comment]
> Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist.

Das ist ja aber kein Socket mein Freund ! Aber ich vermute ein Bug in `bos`. 

In `topkg log` the failing line is [this one](https://github.com/dbuenzli/topkg/blob/master/src-bin/log.ml#L21). In the `topkg lint` case it must be [that one](https://github.com/dbuenzli/topkg/blob/master/src-care/topkg_care_pkg.ml#L325). I suspect I'm doing something with `fd`s that Windows doesn't like.

**Comment by fdopen** [comment]
https://github.com/dbuenzli/bos/blob/6f3a02369dfb92e2032b926688f14767df362e06/src/bos_os_cmd.ml#L47
Unix.file_descr either wraps and handle or an socket. And Unix.set_nonblock is only implemented for sockets, not for file handles. Therefore this obscure message about sockets. (The ocaml runtime should probably check, if you pass a socket or file handle, instead of passing nonsense to a system call,....)

https://github.com/dbuenzli/bos/blob/6f3a02369dfb92e2032b926688f14767df362e06/src/bos_os_cmd.ml#L153
for pipes, `Unix.read` will stop with `Unix.EPIPE` instead of returning zero, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365467(v=vs.85).aspx

https://github.com/dbuenzli/bos/blob/6f3a02369dfb92e2032b926688f14767df362e06/src/bos_os_cmd.ml#L214
`Sys.sigpipe` is not available and therefore `Sys.signal` will always throw an exception.

**Comment by fdopen** [comment]
`topkg clean` doesn't work under linux, too:
`topkg: [ERROR] delete directory _build: _build/src: Is a directory` 
sounds like the error message under windows.

**Comment by dbuenzli** [comment]
> And Unix.set_nonblock is only implemented for sockets, not for file handles.

Ah yes in fact it doesn't make any sense even on Unix to use it on files, I didn't remember that. 

Thanks that all very useful feedback. I think I'll try to setup a vm and debug bos on Windows. The `topkg clean` must be a bug somewhere in [this function](https://github.com/dbuenzli/bos/blob/master/src/bos_os_path.ml#L78) (oddly I never got it on osx).

**Comment by dbuenzli** [comment]
> this function (oddly I never got it on osx).

Ah it seems that on Linux trying to unlink a directory returns `EISDIR` (it's `EPERM` on osx).

**Comment by dbuenzli** [comment]
`topkg` the tool works reasonably well now that bos v1.1.0 is out. Certainly not everything was tested and Windows users are still encouraged to report issues they may run into but the aim of the issue has been fulfilled so I'm closing this.

Thanks again @fdopen for the help and Windows guidance, saves a lot of time.
