### ISSUE TITLE
topkg help contains UNDEFINED

### ISSUE THREAD

**Issue by mor1** [dbuenzli/topkg#35]
Dunno if this is intentional :)

```
: mort@greyjay:~$; topkg help
...
BUGS
       Report them, see UNDEFINED for contact information.
```

**Comment by dbuenzli** [comment]
Yes, pinned topkg packages need topkg-care to be installed for source watermarking to work. Since you are installing topkg-care, you don't have it...

See the [docs here](http://erratique.ch/software/topkg/doc/Topkg.Private.Opam.File.html) if you want to know why this is the case (basically because we need `opam query` https://github.com/ocaml/opam/issues/2446).
