### ISSUE TITLE
Pin to directory does not trigger watermarking

### ISSUE THREAD

**Issue by paurkedal** [dbuenzli/topkg#40]
To test I pinned `topkg` to my local checkout with `opam pin add topkg .`.  The installed `META` still contains `%%VERSION_NUM%%`.  I think the reason is that opam creates a copy of the source directory without the `.git` subdirectory, so `vcs` check in `build_context` fails.

**Comment by dbuenzli** [comment]
There are a two separate issues here: 

1. It will not work with topkg itself because watermarking will only work with topkg-care installed (the reason is explained [here](http://erratique.ch/software/topkg/doc/Topkg.Private.Opam.File.html)). Since topkg-care needs topkg this is not possible. 
2. VCS watermarks only work of course if you have the vcs directory. Current `opam`, by default, will pin in the insane and broken `mixed-mode` pin which does not include the vcs. 

So for watermarking to work in pins you need to 1) install `topkg-care` 2) Pin with `-kgit`

**Comment by paurkedal** [comment]
0. Ah, poor example lying too close to my fingertips.
0. Fair enough.

Thanks for the tip.  `opam pin add blah -kgit .#HEAD` works. The branch was needed, or it would still do a mixed mode pin and inform about doing so. I can do without dirty HEAD pinning.

**Comment by dbuenzli** [comment]
> Thanks for the tip. opam pin add blah -kgit .#HEAD works.

I'd advise to pin to a specific branch (e.g. #master) otherwise like in mixed-mode your opam install is becomes sensitive to the state of your working directory which sounds like a good thing in the short term but is not in the long term when you work with multiple pins.

**Comment by paurkedal** [comment]
I only use this kind of pinning in two cases:
- To test the installation itself, or
- to test that some feature I've been adding serves the need in a dependent project,
before pushing to GH.  You tip works here, since I can always amend the commit before pushing.  In either case the pinning is very short lived.

It's actually ok if the version is "%%VERSION_NUM%%" for this, but I started also using %%NAME%% in the META for the library name, so that I can easily substitute it to create a META for internal linking of tests.
