### ISSUE TITLE
topkg 0.7.1 does not install with system switch

### ISSUE THREAD

**Issue by dsheets** [dbuenzli/topkg#41]
From some other bugs on other trackers (I can't seem to find it...), I have a feeling you already know about this but I thought I'd leave this here so others may know:

```
#=== ERROR while installing topkg.0.7.1 =======================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml pkg/pkg.ml build --pkg-name topkg --installer true
# path         /Users/dsheets/.opam/system/build/topkg.0.7.1
# compiler     system (4.02.3)
# exit-code    2
# env-file     /Users/dsheets/.opam/system/build/topkg.0.7.1/topkg-64213-e7966f.env
# stdout-file  /Users/dsheets/.opam/system/build/topkg.0.7.1/topkg-64213-e7966f.out
# stderr-file  /Users/dsheets/.opam/system/build/topkg.0.7.1/topkg-64213-e7966f.err
### stdout ###
# Cannot find file topfind.
### stderr ###
# Unknown directive `require'.
```

**Comment by dbuenzli** [comment]
You need to apply the fix of https://github.com/ocaml/opam-repository/issues/6579 on your opam repository.

**Comment by szeck87** [comment]
@dbuenzli sorry to comment on a closed issue, but I have something very similar.  The Travis CI tests are failing because it installs ocp-indent via Homebrew, which depends on cmdliner which depends on topkg.  The [build](https://travis-ci.org/szeck87/atom-beautify/jobs/274677244) fails with the exact same error as above.  It's a fork of atom-beautify (package for Atom editor), so there is no opam repository for me to apply a fix to.  Any suggestions?

**Comment by dbuenzli** [comment]
> It's a fork of atom-beautify (package for Atom editor), so there is no opam repository for me to apply a fix to.

Well you are pulling from an opam repository, just make sure that opam-repository has the mentioned fix.
