### ISSUE TITLE
`topkg lint` does not look for recursive _tags file

### ISSUE THREAD

**Issue by samoht** [dbuenzli/topkg#45]
See https://github.com/mirage/mirage-http/pull/25

```
$ topkg lint
[ ... ]
[FAIL] File opam and _tags dependency check:
       channel: opam present but _tags absent
       cohttp: opam present but _tags absent
       lwt: opam present but _tags absent
       mirage-conduit: opam present but _tags absent
       mirage-types-lwt: opam present but _tags absent
```

Some of them are false positive because name of ocamlfind library and opam package is different (and I don't really expect topkg to guess that) but the rest is just because I'm using  `_tags` and src/_tags` files.

**Comment by dbuenzli** [comment]
> Some of them are false positive because name of ocamlfind library and opam package is different

Note, the false positive can be turned off by declaring your `opam` file [manually](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALopam_file) to `topkg`.

**Comment by dbuenzli** [comment]
Btw. this is a quite funny example that shows that end-users usually don't know what they want. 

Most people complain to me about `ocamlbuild` that it splits its definitions into multiple files. But then what do they do ? They do this for *no reason*. 

In your case you should just delete that `src/_tags` have a single `_tags` file with: 
```
<src/**>: package(lwt), package(channel), package(cohttp.lwt-core)
<src/**>: package(conduit.mirage), package(mirage-types.lwt)
```

So I won't fix this because I think you should use a single `_tags` file for your package --- we don't like that `ocamlbuild` splits its definition into multiple files RIGHT ?

Feel free to reopen if there's a more compelling use case.
