### ISSUE TITLE
ocamldoc -intro support

### ISSUE THREAD

**Issue by avsm** [dbuenzli/topkg#70]
It would be useful to be able to specify an intro file for the generated documentation.  My usecase is to add a link to an iocamljs notebook that is also generated as part of the build process.

**Comment by dbuenzli** [comment]
I would rather suggest to add this link in the preamble of the namespacing module (or one of the toplevel modules) of your package. 

Currently `odig` won't support this and I don't think I'll provide a way to customize the package landing page so that we get a bit of uniformity for the end-user (it's not excluded however that I provide a way to specify an introductory section). 

Also the `odoc` story is not clear on that front yet see https://github.com/ocaml-doc/odoc/issues/12

**Comment by dbuenzli** [comment]
Just to be clear, this was closed so that the scheme you design for your docs also works when people use `odig` locally. You may also be interested by https://github.com/dbuenzli/odig/issues/6
