### ISSUE TITLE
Allow building mllibs without cmxs

### ISSUE THREAD

**Issue by stedolan** [dbuenzli/topkg#96]
`Pkg.mllib` currently builds a `.cma`, `.cmxa` and `.cmxs` out of a `.mllib` specification. I'd like to be able to choose which targets are built (in particular, to avoid building `.cmxs` in situations where it doesn't make sense)

**Comment by dbuenzli** [comment]
For some reason this breaks the build of `ptime`.

**Comment by dbuenzli** [comment]
So it seems there's a missing dependency between `somelib.a` and `somelib.cmxs` and a20b81b slightly changed the *order* on which targets to the single `topkg` invocation are given on the cli. The old order, combined with `ocamlbuild`'s poor parallelism made the build work.

It checked the build succeeds with the upcoming [`ocamlbuild` 0.11.0](https://github.com/ocaml/ocamlbuild/issues/176) sports a new rule to generate a `.cmxs` from a `.mllib`. Apparently it has the right deps.

Meanwhile I'm going to revert to the previous invocation order so that `ptime` does not break. 

Boy our build systems are brittle.
